import sqlite3
import os
import asyncio
import telegram
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()


def init_db():
    conn = sqlite3.connect("logs.db")
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS posts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            topic TEXT,
            tweet TEXT,
            characters INTEGER,
            status TEXT,
            timestamp TEXT
        )
    """)
    conn.commit()
    conn.close()
    print("Agent 3: Database ready")


def log_to_db(topic, tweet, status):
    conn = sqlite3.connect("logs.db")
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO posts (topic, tweet, characters, status, timestamp)
        VALUES (?, ?, ?, ?, ?)
    """, (topic, tweet, len(tweet), status, datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
    conn.commit()
    conn.close()
    print(f"Agent 3: Logged to database → status: {status}")


async def send_to_telegram(topic, tweet, image_path):
    bot = telegram.Bot(token=os.getenv("TELEGRAM_BOT_TOKEN"))
    chat_id = os.getenv("TELEGRAM_CHAT_ID")

    message = f"""
🤖 Auto-generated post

📌 Topic: {topic}

{tweet}

⏰ {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    """

    if image_path and os.path.exists(image_path):
        with open(image_path, "rb") as img:
            await bot.send_photo(chat_id=chat_id, photo=img, caption=message)
        print("Agent 3: Sent image + text to Telegram!")
    else:
        await bot.send_message(chat_id=chat_id, text=message)
        print("Agent 3: Sent text only to Telegram!")


def post_to_instagram(topic, tweet, image_path):
    print("Agent 3: Posting to Instagram...")

    try:
        from instagrapi import Client
        import time

        username = os.getenv("INSTAGRAM_USERNAME")
        password = os.getenv("INSTAGRAM_PASSWORD")

        if not username or not password:
            print("Agent 3: Instagram credentials missing, skipping...")
            return False

        if not image_path or not os.path.exists(image_path):
            print("Agent 3: No image found, skipping Instagram post...")
            return False

        cl = Client()
        cl.delay_range = [2, 5]
        session_file = "instagram_session.json"

        if os.path.exists(session_file):
            try:
                cl.load_settings(session_file)
                cl.login(username, password)
                print("Agent 3: Instagram login via session successful!")
            except Exception:
                print("Agent 3: Session expired, logging in fresh...")
                os.remove(session_file)
                cl = Client()
                cl.delay_range = [2, 5]
                cl.login(username, password)
                cl.dump_settings(session_file)
                print("Agent 3: Fresh login successful, session saved!")
        else:
            cl.login(username, password)
            cl.dump_settings(session_file)
            print("Agent 3: Instagram login successful, session saved!")

        # detailed instagram caption
        hashtags = " ".join([w for w in tweet.split() if w.startswith("#")])
        clean_body = tweet.split("#")[0].strip()

        caption = f"""📌 {topic}

{clean_body}

━━━━━━━━━━━━━━━━━━
{hashtags}
━━━━━━━━━━━━━━━━━━
🤖 Auto-generated by AI Agent
⏰ {datetime.now().strftime('%d %B %Y  |  %H:%M')}
━━━━━━━━━━━━━━━━━━
#AutoGenerated #AIContent #TrendingNow #BreakingNews"""

        time.sleep(3)
        cl.photo_upload(image_path, caption=caption)
        print("Agent 3: Posted to Instagram successfully!")
        cl.logout()
        return True

    except Exception as e:
        print(f"Agent 3: Instagram posting failed → {e}")
        return False


def run_distribution_agent(topic, tweet, image_path=None, platform="both"):
    print("Agent 3: Starting distribution...")
    print(f"Agent 3: Platform mode → {platform}")

    init_db()

    telegram_status = "skipped"
    instagram_status = "skipped"

    if platform in ["telegram", "both"]:
        try:
            asyncio.run(send_to_telegram(topic, tweet, image_path))
            telegram_status = "success"
        except Exception as e:
            print(f"Agent 3: Telegram failed → {e}")
            telegram_status = "failed"

    if platform in ["instagram", "both"]:
        result = post_to_instagram(topic, tweet, image_path)
        instagram_status = "success" if result else "failed"

    status = "success" if (telegram_status in ["success", "skipped"] and
                           instagram_status in ["success", "skipped"]) else "failed"

    log_to_db(topic, tweet, status)

    print(f"Agent 3: Telegram  → {telegram_status}")
    print(f"Agent 3: Instagram → {instagram_status}")
    print(f"Agent 3: Done! Overall status → {status}")
    return status


if __name__ == "__main__":
    sample_topic = "ChatGPT"
    sample_tweet = "AI is transforming how we work. ChatGPT is leading the charge. #ChatGPT #AI #FutureOfWork"
    status = run_distribution_agent(sample_topic, sample_tweet, "posts/post_test.jpg")
    print("\n--- Final Output ---")
    print(f"Status : {status}")